import streamlit as st
import pandas as pd
from fpdf import FPDF
import os

st.title("Dark Watch Intelligence Dashboard")

# 1. Load Data
# We look for the 'results.csv' file generated by your scraper
if os.path.exists("results.csv"):
    df = pd.read_csv("results.csv")
    st.dataframe(df)
    
    # 2. CSV Download Button
    csv = df.to_csv(index=False).encode('utf-8')
    st.download_button("Download Data as CSV", csv, "leads.csv", "text/csv")

    # 3. PDF Generation
    if st.button("Generate PDF Report"):
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(200, 10, txt="Security Leads Report", ln=True, align='C')
        pdf.set_font("Arial", size=12)
        pdf.ln(10)
        
        # Add rows from the dataframe to the PDF
        for index, row in df.iterrows():
            row_text = f"{row.to_string()}"
            pdf.multi_cell(0, 10, txt=row_text)
            pdf.ln(5)
            
        pdf_output = pdf.output(dest='S').encode('latin-1')
        st.download_button("Download PDF Report", pdf_output, "leads.pdf", "application/pdf")
else:
    st.warning("No 'results.csv' file found. Run your scraper first!")
